package utn.frba.dds.externo;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class RepositorioCGPExterno {

	private List<CentroDTO> cgps;

	public RepositorioCGPExterno() {
		cgps = new ArrayList<CentroDTO>();
		this.buildCGPs();
	}

	private void buildCGPs() {

		cgps.add(new CGPBuilder(1)
				.setZonas("Retiro - San Nicolas - Puerto Madero - San Telmo - Montserrat y Constitución")
				.setDirector("Jose Campanella").setDomicilio("Av. Uruguay 740").setTelefono("4370-9700")
				.agregarServicio(new ServicioGestionBuilder("Mesa de informes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Gestion Urbanistica")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Participación Ciudadana")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Defensoría de niños, niñas y adolescentes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 16, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Apoyo escolar")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 16, 30, 19, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("EcoBici")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 8, 30, 17, 30)).build())
				.build());

		cgps.add(new CGPBuilder(2).setZonas("Recoleta").setDirector("Jose Campanella")
				.setDomicilio("Pres. José E. Uriburu 1022").setTelefono("4823-1165")
				.agregarServicio(new ServicioGestionBuilder("Mesa de informes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Gestion Urbanistica")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Participación Ciudadana")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Defensoría de niños, niñas y adolescentes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 16, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Apoyo escolar")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 16, 30, 19, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("EcoBici")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 8, 30, 17, 30)).build())
				.build());

		cgps.add(new CGPBuilder(3).setZonas("Balvanera - San Cristobal").setDirector("Jose Campanella")
				.setDomicilio("Junín 521").setTelefono("4375-0644")
				.agregarServicio(new ServicioGestionBuilder("Mesa de informes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Gestion Urbanistica")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Participación Ciudadana")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Defensoría de niños, niñas y adolescentes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 16, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Apoyo escolar")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 16, 30, 19, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("EcoBici")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 8, 30, 17, 30)).build())
				.build());

		cgps.add(new CGPBuilder(4).setZonas("La Boca - Barracas - Parque Patricios y Nueva Pompeya ")
				.setDirector("Jose Campanella").setDomicilio("Av. del Barco Centenera 2906").setTelefono("4918-1815")
				.agregarServicio(new ServicioGestionBuilder("Mesa de informes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Gestion Urbanistica")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Participación Ciudadana")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Defensoría de niños, niñas y adolescentes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 16, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Apoyo escolar")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 16, 30, 19, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("EcoBici")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 8, 30, 17, 30)).build())
				.build());

		cgps.add(new CGPBuilder(5).setZonas("Almagro y Boedo").setDirector("Jose Campanella")
				.setDomicilio("Carlos Calvo 3307").setTelefono("4931-6699")
				.agregarServicio(new ServicioGestionBuilder("Mesa de informes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Gestion Urbanistica")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Participación Ciudadana")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Defensoría de niños, niñas y adolescentes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 16, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Apoyo escolar")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 16, 30, 19, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("EcoBici")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 8, 30, 17, 30)).build())
				.build());

		cgps.add(new CGPBuilder(6).setZonas("Caballito").setDirector("Jose Campanella")
				.setDomicilio("Patricias Argentinas 277").setTelefono("4958-6504")
				.agregarServicio(new ServicioGestionBuilder("Mesa de informes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Gestion Urbanistica")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Participación Ciudadana")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Defensoría de niños, niñas y adolescentes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 16, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Apoyo escolar")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 16, 30, 19, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("EcoBici")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 8, 30, 17, 30)).build())
				.build());

		cgps.add(new CGPBuilder(7).setZonas("Flores y Parque Chacabuco").setDirector("Jose Campanella")
				.setDomicilio("Av. Rivadavia 7202").setTelefono("4637-2355")
				.agregarServicio(new ServicioGestionBuilder("Mesa de informes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Gestion Urbanistica")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Participación Ciudadana")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Defensoría de niños, niñas y adolescentes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 16, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 16, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("EcoBici")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 8, 30, 17, 30)).build())
				.build());

		cgps.add(new CGPBuilder(8).setZonas("Villa Soldati - Villa Riachuelo y Villa Lugano")
				.setDirector("Jose Campanella").setDomicilio("Av. Roca 5252").setTelefono("4605-1735")
				.agregarServicio(new ServicioGestionBuilder("Mesa de informes")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Gestion Urbanistica")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 9, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 9, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Dirección de Participación Ciudadana")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 10, 0, 18, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 10, 0, 18, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("Apoyo escolar")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 16, 30, 19, 0))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 16, 30, 19, 0)).build())
				.agregarServicio(new ServicioGestionBuilder("EcoBici")
						.agregarHorarioDisponible(new RangoServicioDTO(1, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(2, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(3, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(4, 8, 30, 17, 30))
						.agregarHorarioDisponible(new RangoServicioDTO(5, 8, 30, 17, 30)).build())
				.build());
	}

	public List<CentroDTO> buscarCGPs(String criterio) {
		return cgps.stream().filter(cgp -> cgp.matchea(criterio)).collect(Collectors.toList());
	}

}
